# Generated by Django 4.2 on 2023-04-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_offer_offerhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(max_length=255),
        ),
    ]
