# Generated by Django 4.2 on 2023-04-28 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_alter_offer_offer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerhistory',
            name='competitor_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competitor_offer', to='src.offer'),
        ),
        migrations.AlterField(
            model_name='offerhistory',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_offer', to='src.offer'),
        ),
    ]
