# Generated by Django 4.2 on 2023-04-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_alter_offerhistory_competitor_offer_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['offer_id'], name='offerbot_of_offer_i_8354d4_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status', 'owner_type'], name='offerbot_of_status_dd62d9_idx'),
        ),
    ]
