# Generated by Django 4.2 on 2023-07-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_currencyconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticationtoken',
            name='provider',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='authenticationtoken',
            name='provider_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
