# Generated by Django 4.2 on 2023-07-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_offer_provider_offer_provider_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyconfig',
            name='provider',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='currencyconfig',
            name='provider_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
