# Generated by Django 4.2 on 2023-07-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_currencyconfig_provider_currencyconfig_provider_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currencyconfig',
            unique_together={('currency', 'name', 'provider')},
        ),
    ]
