# Generated by Django 4.2 on 2023-08-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_alter_currencyconfig_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_id',
            field=models.CharField(max_length=255),
        ),
    ]
