NOONES_AUTHENTICATION_TOKEN_CACHE_KEY = 'NOONES_AUTHENTICATION_TOKEN'
NOONES_AUTHENTICATION_TOKEN_VALIDITY_TIMEDELTA_HRS = 24

CMC_CURRENCY_MARKET_PRICE_CACHE_KEY = 'CMC_CURRENCY_MARKET_PRICE_{crypto_currency}_{conversion_fiat_currency}'
CMC_CURRENCY_MARKET_PRICE_CACHE_TTL = 300

CACHE_MAX_TTL = 3600  # 1h
